// <auto-generated />
using System;
using Cuisinier.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cuisinier.Infrastructure.Migrations
{
    [DbContext(typeof(CuisinierDbContext))]
    [Migration("20251229212416_AjouterParametresGenerationJson")]
    partial class AjouterParametresGenerationJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cuisinier.Core.Entities.IngredientRecette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecetteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecetteId");

                    b.ToTable("IngredientRecettes");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.ItemListeCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstAjouteManuellement")
                        .HasColumnType("bit");

                    b.Property<int>("ListeCourseId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListeCourseId");

                    b.ToTable("ItemListeCourses");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.ListeCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("ListeCourses");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebutSemaine")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParametresGenerationJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DateDebutSemaine");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.Recette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionComplete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstDeLaBaseDeDonnees")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Personnes")
                        .HasColumnType("int");

                    b.Property<int?>("PlatOriginalId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TempsCuisson")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TempsPreparation")
                        .HasColumnType("time");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("PlatOriginalId");

                    b.ToTable("Recettes");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.IngredientRecette", b =>
                {
                    b.HasOne("Cuisinier.Core.Entities.Recette", "Recette")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.ItemListeCourse", b =>
                {
                    b.HasOne("Cuisinier.Core.Entities.ListeCourse", "ListeCourse")
                        .WithMany("Items")
                        .HasForeignKey("ListeCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeCourse");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.ListeCourse", b =>
                {
                    b.HasOne("Cuisinier.Core.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.Recette", b =>
                {
                    b.HasOne("Cuisinier.Core.Entities.Menu", "Menu")
                        .WithMany("Recettes")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuisinier.Core.Entities.Recette", "PlatOriginal")
                        .WithMany()
                        .HasForeignKey("PlatOriginalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Menu");

                    b.Navigation("PlatOriginal");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.ListeCourse", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.Menu", b =>
                {
                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("Cuisinier.Core.Entities.Recette", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
