// <auto-generated />
using System;
using Cuisinier.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cuisinier.Infrastructure.Migrations
{
    [DbContext(typeof(CuisinierDbContext))]
    [Migration("20260111171253_MigrateDishesFromTestUserToSecondUser")]
    partial class MigrateDishesFromTestUserToSecondUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This migration only migrates data, no model changes
            // The model snapshot remains the same as MakeDishUserIdNullable
            // The BuildTargetModel is intentionally empty as this is a data-only migration
#pragma warning restore 612, 618
        }
    }
}
