using Cuisinier.Core.DTOs;
using Cuisinier.Api.Services;

namespace Cuisinier.Api.Endpoints;

public static class MenuEndpoints
{
    public static void MapMenuEndpoints(this WebApplication app)
    {
        var group = app.MapGroup("/api/menu");

        group.MapPost("/generate", GenerateMenu)
            .WithName("GenerateMenu")
            .WithSummary("Generate a new weekly menu")
            .WithDescription("Starts generating a weekly menu in the background based on provided parameters. Returns immediately with menu ID. Use SignalR to receive notification when generation is complete.")
            .Produces<MenuGenerationResponse>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status400BadRequest)
            .Produces(StatusCodes.Status500InternalServerError);

        group.MapGet("/last-parameters", GetLastParameters)
            .WithName("GetLastParameters")
            .WithSummary("Get last saved menu parameters")
            .WithDescription("Retrieves the last saved menu generation parameters from cache or database.")
            .Produces<MenuParameters?>(StatusCodes.Status200OK);

        group.MapPost("/parameters", SaveParameters)
            .WithName("SaveParameters")
            .WithSummary("Save menu parameters")
            .WithDescription("Saves menu generation parameters for future use.")
            .Produces(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status400BadRequest);

        group.MapGet("/{id:int}", GetMenu)
            .WithName("GetMenu")
            .WithSummary("Get menu by ID")
            .WithDescription("Retrieves a specific menu with all its recipes and ingredients.")
            .Produces<MenuResponse>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound);

        group.MapGet("", GetAllMenus)
            .WithName("GetAllMenus")
            .WithSummary("Get all validated menus")
            .WithDescription("Retrieves all validated menus (menus that have a shopping list), ordered by week start date descending.")
            .Produces<List<MenuResponse>>(StatusCodes.Status200OK);

        group.MapPost("/{menuId:int}/recipe/{recipeId:int}/replace", ReplaceRecipe)
            .WithName("ReplaceRecipe")
            .WithSummary("Replace a recipe in a menu")
            .WithDescription("Replaces an existing recipe in a menu with a new one generated by AI.")
            .Produces<RecipeResponse>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .Produces(StatusCodes.Status400BadRequest);

        group.MapPost("/{menuId:int}/recipe/{recipeId:int}/ingredient/replace", ReplaceIngredient)
            .WithName("ReplaceIngredient")
            .WithSummary("Replace an ingredient in a recipe")
            .WithDescription("Replaces an ingredient in a recipe with a new one.")
            .Produces<RecipeResponse>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .Produces(StatusCodes.Status400BadRequest);

        group.MapPost("/{menuId:int}/favorite/{favoriteId:int}", AddFavoriteToMenu)
            .WithName("AddFavoriteToMenu")
            .WithSummary("Add a favorite recipe to a menu")
            .WithDescription("Adds a favorite recipe to an existing menu.")
            .Produces<RecipeResponse>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound);

        group.MapDelete("/{menuId:int}/recipe/{recipeId:int}", DeleteRecipe)
            .WithName("DeleteRecipe")
            .WithSummary("Delete a recipe from a menu")
            .WithDescription("Deletes a recipe from a menu.")
            .Produces(StatusCodes.Status204NoContent)
            .Produces(StatusCodes.Status404NotFound);

        group.MapDelete("/{menuId:int}", DeleteMenu)
            .WithName("DeleteMenu")
            .WithSummary("Delete a menu")
            .WithDescription("Deletes a menu and all its associated recipes.")
            .Produces(StatusCodes.Status204NoContent)
            .Produces(StatusCodes.Status404NotFound);

        group.MapPost("/{menuId:int}/validate", ValidateMenu)
            .WithName("ValidateMenu")
            .WithSummary("Validate a menu")
            .WithDescription("Validates a menu by generating its shopping list and launching background detailed recipe generation.")
            .Produces<MenuResponse>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .Produces(StatusCodes.Status500InternalServerError);
    }

    private static async Task<IResult> GenerateMenu(
        MenuGenerationRequest request,
        IMenuService menuService,
        BackgroundMenuService backgroundMenuService)
    {
        // Create a temporary menu and launch generation in background
        var menuId = await menuService.StartMenuGenerationAsync(request);
        var response = new MenuGenerationResponse
        {
            MenuId = menuId,
            Status = "generating"
        };
        
        // Launch generation in background (fire-and-forget)
        backgroundMenuService.StartGenerateMenuInBackground(menuId, request);
        
        return Results.Ok(response);
    }

    private static async Task<IResult> GetMenu(
        int id,
        IMenuService menuService)
    {
        var menu = await menuService.GetMenuAsync(id);
        
        if (menu == null)
        {
            return Results.NotFound();
        }

        return Results.Ok(menu);
    }

    private static async Task<IResult> GetLastParameters(IMenuService menuService)
    {
        var parameters = await menuService.GetLastParametersAsync();
        return Results.Ok(parameters);
    }

    private static async Task<IResult> SaveParameters(
        MenuParameters parameters,
        IMenuService menuService)
    {
        await menuService.SaveParametersAsync(parameters);
        return Results.Ok();
    }

    private static async Task<IResult> GetAllMenus(IMenuService menuService)
    {
        var menus = await menuService.GetAllMenusAsync();
        return Results.Ok(menus);
    }

    private static async Task<IResult> ReplaceRecipe(
        int menuId,
        int recipeId,
        RecipeReplacementRequest request,
        IMenuService menuService)
    {
        var recipe = await menuService.ReplaceRecipeAsync(menuId, recipeId, request);
        return Results.Ok(recipe);
    }

    private static async Task<IResult> ReplaceIngredient(
        int menuId,
        int recipeId,
        IngredientReplacementRequest request,
        IMenuService menuService)
    {
        var recipe = await menuService.ReplaceIngredientAsync(menuId, recipeId, request);
        return Results.Ok(recipe);
    }

    private static async Task<IResult> AddFavoriteToMenu(
        int menuId,
        int favoriteId,
        IMenuService menuService)
    {
        var recipe = await menuService.AddFavoriteToMenuAsync(menuId, favoriteId);
        return Results.Ok(recipe);
    }

    private static async Task<IResult> DeleteRecipe(
        int menuId,
        int recipeId,
        IMenuService menuService)
    {
        await menuService.DeleteRecipeAsync(menuId, recipeId);
        return Results.NoContent();
    }

    private static async Task<IResult> DeleteMenu(
        int menuId,
        IMenuService menuService)
    {
        await menuService.DeleteMenuAsync(menuId);
        return Results.NoContent();
    }

    private static async Task<IResult> ValidateMenu(
        int menuId,
        ValidateMenuRequest? request,
        IMenuService menuService)
    {
        var menu = await menuService.ValidateMenuAsync(menuId, request);
        return Results.Ok(menu);
    }
}

